### ISSUE TITLE
when you enter the game, the PSP reboots

### ISSUE THREAD

**Issue by loydgr** [xerpi/psp-uvc-usb-video-class#6] opened 2021-01-24 10:02 UTC
when i enter the game, the psp reboots. the problem is in the plugin itself, did everything right. the recording is only in the interface.

**Comment by xerpi** [comment] 2021-01-24 11:02
Duplicate of https://github.com/xerpi/psp-uvc-usb-video-class/issues/2.

**Closed as completed by xerpi** 2021-01-24 11:02 UTC
