### ISSUE TITLE
Can't launch plugin at all on PSP GO

### ISSUE THREAD

**Issue by Baluu2001** [xerpi/psp-uvc-usb-video-class#3] opened 2020-10-04 00:35 UTC
Hello.I Tried To run this plugin on my psp go.I have tried both of ms0 and ef0 paths in seplugins VSH.TXT AND GAME.TXT but nothing at all.Launched PotPlayer and tried to run stream from a webcam,it says no video device,in obs the same problem.Installed everything correctly,reinstalled it,still no result.Can You Give me some advice,because I don't have any more ideas...

**Comment by xerpi** [comment] 2020-10-04 07:20
I think this is a duplicate of: https://github.com/xerpi/psp-uvc-usb-video-class/issues/1

**Closed as completed by xerpi** 2020-10-04 07:20 UTC

**Comment by xerpi** [comment] 2020-10-04 10:20
Try with 0.2: https://github.com/xerpi/psp-uvc-usb-video-class/releases

**Comment by Baluu2001** [comment] 2020-10-04 10:47
> Try with 0.2: https://github.com/xerpi/psp-uvc-usb-video-class/releases

thanks,it worked!!!
